-- ============================================================
-- Dark Matter RP - Full Website + Store Supervisor Setup
-- شغّل الملف كاملاً داخل Supabase > SQL Editor
-- آمن للتشغيل على مشروع جديد أو المشروع الحالي.
-- ============================================================

create extension if not exists pgcrypto;

-- 1) الموقع / الصلاحيات
create table if not exists public.site_admins (
  email text primary key,
  created_at timestamptz not null default now()
);

create table if not exists public.supervisors (
  email text primary key,
  added_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

insert into public.site_admins(email)
values ('alarmierahmed@gmail.com'), ('akkkx58@gmail.com')
on conflict (email) do nothing;

create or replace function public.is_site_owner()
returns boolean
language sql stable security definer set search_path=public
as $$
  select exists(
    select 1 from public.site_admins
    where lower(email)=lower(coalesce(auth.jwt()->>'email',''))
  );
$$;

create or replace function public.is_site_supervisor()
returns boolean
language sql stable security definer set search_path=public
as $$
  select exists(
    select 1 from public.supervisors
    where lower(email)=lower(coalesce(auth.jwt()->>'email',''))
  );
$$;

grant execute on function public.is_site_owner() to authenticated;
grant execute on function public.is_site_supervisor() to authenticated;

-- 2) الطلبات
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text unique default ('DM-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,8))),
  buyer_id uuid not null references auth.users(id) on delete cascade,
  buyer_email text,
  buyer_name text,
  product_name text not null,
  price numeric(10,2) not null default 0,
  status text not null default 'بانتظار فتح التكت',
  payment_status text not null default 'ticket',
  payment_id text,
  received_by uuid references auth.users(id) on delete set null,
  received_by_email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.orders add column if not exists product_id bigint;
alter table public.orders add column if not exists original_price numeric(10,2);
alter table public.orders add column if not exists discount_code text;
alter table public.orders add column if not exists discount_amount numeric(10,2) not null default 0;

-- 3) إعدادات المتجر
create table if not exists public.store_settings (
  id integer primary key default 1 check (id=1),
  store_title text not null default 'المتجر',
  store_subtitle text not null default 'اختر السيارة المناسبة وأضفها إلى السلة، وبعد إرسال الطلب افتح تكت المتجر للاستلام.',
  announcement text not null default '',
  ticket_message text not null default 'تم إنشاء طلبك بنجاح — افتح تكت المتجر لاستلام الطلب.',
  ticket_url text not null default 'https://discord.gg/drme',
  store_enabled boolean not null default true,
  updated_at timestamptz not null default now()
);

alter table public.store_settings add column if not exists ticket_message text not null default 'تم إنشاء طلبك بنجاح — افتح تكت المتجر لاستلام الطلب.';
alter table public.store_settings add column if not exists ticket_url text not null default 'https://discord.gg/drme';

insert into public.store_settings(id,store_subtitle,ticket_message,ticket_url)
values (1,'اختر السيارة المناسبة وأضفها إلى السلة، وبعد إرسال الطلب افتح تكت المتجر للاستلام.','تم إنشاء طلبك بنجاح — افتح تكت المتجر لاستلام الطلب.','https://discord.gg/drme')
on conflict (id) do update set
  store_subtitle=excluded.store_subtitle,
  ticket_message=excluded.ticket_message,
  ticket_url=excluded.ticket_url;

-- 4) السيارات والمنتجات
create table if not exists public.store_products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null default 'car',
  description text not null default '',
  price numeric(10,2) not null default 22.99 check(price>=0),
  image_url text not null default '',
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- حذف الهليكوبتر وطاولة التصنيع من أي نسخة قديمة.
delete from public.store_products where id in (1,2) or category in ('helicopter','crafting');

alter table public.store_products drop constraint if exists store_products_category_check;
alter table public.store_products add constraint store_products_category_check check(category in ('car','other'));

-- زرع السيارات الافتراضية فقط (الصور موجودة داخل index.html كنسخة احتياطية).
insert into public.store_products(id,name,category,price,sort_order)
select i, 'سيارة خاصة '||i, 'car', 22.99, i
from generate_series(3,42) as i
on conflict (id) do nothing;

select setval(
  pg_get_serial_sequence('public.store_products','id'),
  greatest((select coalesce(max(id),42) from public.store_products),42),
  true
);

-- 5) أكواد الخصم
create table if not exists public.discount_codes (
  id uuid primary key default gen_random_uuid(),
  code text not null,
  discount_type text not null check(discount_type in ('percent','fixed')),
  discount_value numeric(10,2) not null check(discount_value>=0),
  min_order numeric(10,2) not null default 0 check(min_order>=0),
  max_uses integer null check(max_uses is null or max_uses>=1),
  used_count integer not null default 0 check(used_count>=0),
  starts_at timestamptz null,
  expires_at timestamptz null,
  active boolean not null default true,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists discount_codes_code_lower_uidx
on public.discount_codes(lower(code));

create or replace function public.is_store_staff()
returns boolean
language sql stable security definer set search_path=public
as $$ select public.is_site_owner() or public.is_site_supervisor(); $$;

grant execute on function public.is_store_staff() to authenticated;

-- 6) RLS
alter table public.site_admins enable row level security;
alter table public.supervisors enable row level security;
alter table public.orders enable row level security;
alter table public.store_settings enable row level security;
alter table public.store_products enable row level security;
alter table public.discount_codes enable row level security;

-- owner
 drop policy if exists "site_admins_read_owner" on public.site_admins;
create policy "site_admins_read_owner" on public.site_admins for select to authenticated
using(public.is_site_owner() or lower(email)=lower(coalesce(auth.jwt()->>'email','')));

-- supervisors
 drop policy if exists "supervisors_read_self_or_owner" on public.supervisors;
 drop policy if exists "supervisors_insert_owner" on public.supervisors;
 drop policy if exists "supervisors_delete_owner" on public.supervisors;
create policy "supervisors_read_self_or_owner" on public.supervisors for select to authenticated
using(public.is_site_owner() or lower(email)=lower(coalesce(auth.jwt()->>'email','')));
create policy "supervisors_insert_owner" on public.supervisors for insert to authenticated
with check(public.is_site_owner());
create policy "supervisors_delete_owner" on public.supervisors for delete to authenticated
using(public.is_site_owner());

-- orders
 drop policy if exists "orders_insert_buyer" on public.orders;
 drop policy if exists "buyer creates own order" on public.orders;
 drop policy if exists "orders_select_buyer_or_staff" on public.orders;
 drop policy if exists "orders_update_staff" on public.orders;
 drop policy if exists "orders_delete_owner" on public.orders;
create policy "orders_select_buyer_or_staff" on public.orders for select to authenticated
using(buyer_id=auth.uid() or public.is_store_staff());
create policy "orders_update_staff" on public.orders for update to authenticated
using(public.is_store_staff()) with check(public.is_store_staff());
create policy "orders_delete_owner" on public.orders for delete to authenticated
using(public.is_site_owner());

-- store settings
 drop policy if exists "store settings public read" on public.store_settings;
 drop policy if exists "store settings staff update" on public.store_settings;
create policy "store settings public read" on public.store_settings for select to anon,authenticated using(true);
create policy "store settings staff update" on public.store_settings for update to authenticated
using(public.is_store_staff()) with check(public.is_store_staff());

-- products
 drop policy if exists "store products public active read" on public.store_products;
 drop policy if exists "store products staff all read" on public.store_products;
 drop policy if exists "store products staff insert" on public.store_products;
 drop policy if exists "store products staff update" on public.store_products;
 drop policy if exists "store products staff delete" on public.store_products;
create policy "store products public active read" on public.store_products for select to anon,authenticated using(active=true);
create policy "store products staff all read" on public.store_products for select to authenticated using(public.is_store_staff());
create policy "store products staff insert" on public.store_products for insert to authenticated with check(public.is_store_staff());
create policy "store products staff update" on public.store_products for update to authenticated using(public.is_store_staff()) with check(public.is_store_staff());
create policy "store products staff delete" on public.store_products for delete to authenticated using(public.is_store_staff());

-- discounts
 drop policy if exists "discount staff read" on public.discount_codes;
 drop policy if exists "discount staff insert" on public.discount_codes;
 drop policy if exists "discount staff update" on public.discount_codes;
 drop policy if exists "discount staff delete" on public.discount_codes;
create policy "discount staff read" on public.discount_codes for select to authenticated using(public.is_store_staff());
create policy "discount staff insert" on public.discount_codes for insert to authenticated with check(public.is_store_staff());
create policy "discount staff update" on public.discount_codes for update to authenticated using(public.is_store_staff()) with check(public.is_store_staff());
create policy "discount staff delete" on public.discount_codes for delete to authenticated using(public.is_store_staff());

-- 7) إنشاء طلب آمن من سعر قاعدة البيانات.
create or replace function public.create_store_order(p_product_id bigint,p_discount_code text default null)
returns public.orders
language plpgsql security definer set search_path=public
as $$
declare
  p public.store_products%rowtype;
  d public.discount_codes%rowtype;
  settings public.store_settings%rowtype;
  discount_value_calc numeric(10,2):=0;
  final_price numeric(10,2);
  result_order public.orders%rowtype;
  code_clean text:=nullif(upper(trim(coalesce(p_discount_code,''))),'');
  buyer_email_value text:=lower(coalesce(auth.jwt()->>'email',''));
  buyer_name_value text:=coalesce(auth.jwt()->'user_metadata'->>'full_name',auth.jwt()->'user_metadata'->>'name',auth.jwt()->'user_metadata'->>'user_name',buyer_email_value);
begin
  if auth.uid() is null then raise exception 'يجب تسجيل الدخول أولاً'; end if;
  select * into settings from public.store_settings where id=1;
  if settings.id is not null and not settings.store_enabled then raise exception 'المتجر مغلق حالياً'; end if;
  select * into p from public.store_products where id=p_product_id and active=true;
  if p.id is null then raise exception 'المنتج غير موجود أو غير متاح'; end if;
  final_price:=p.price;

  if code_clean is not null then
    select * into d from public.discount_codes where upper(code)=code_clean limit 1;
    if d.id is null then raise exception 'كود الخصم غير صحيح'; end if;
    if not d.active then raise exception 'كود الخصم غير مفعل'; end if;
    if d.starts_at is not null and now()<d.starts_at then raise exception 'كود الخصم لم يبدأ بعد'; end if;
    if d.expires_at is not null and now()>d.expires_at then raise exception 'انتهت صلاحية كود الخصم'; end if;
    if d.max_uses is not null and d.used_count>=d.max_uses then raise exception 'تم استهلاك كود الخصم'; end if;
    if p.price<d.min_order then raise exception 'سعر المنتج أقل من الحد الأدنى للكود'; end if;
    if d.discount_type='percent' then discount_value_calc:=round(p.price*least(d.discount_value,100)/100.0,2);
    else discount_value_calc:=least(d.discount_value,p.price); end if;
    final_price:=greatest(0,round(p.price-discount_value_calc,2));
    update public.discount_codes set used_count=used_count+1,updated_at=now() where id=d.id;
  end if;

  insert into public.orders(
    buyer_id,buyer_email,buyer_name,product_id,product_name,original_price,discount_code,
    discount_amount,price,status,payment_status,updated_at
  ) values(
    auth.uid(),buyer_email_value,buyer_name_value,p.id,p.name,p.price,code_clean,
    discount_value_calc,final_price,'بانتظار فتح التكت','ticket',now()
  ) returning * into result_order;
  return result_order;
end;
$$;

revoke all on function public.create_store_order(bigint,text) from public;
grant execute on function public.create_store_order(bigint,text) to authenticated;

-- 8) رفع صور المنتجات من لوحة المشرفين
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('store-images','store-images',true,10485760,array['image/jpeg','image/png','image/webp','image/gif'])
on conflict(id) do update set public=true,file_size_limit=10485760,allowed_mime_types=excluded.allowed_mime_types;

 drop policy if exists "store images public read" on storage.objects;
 drop policy if exists "store images staff insert" on storage.objects;
 drop policy if exists "store images staff update" on storage.objects;
 drop policy if exists "store images staff delete" on storage.objects;
create policy "store images public read" on storage.objects for select to public using(bucket_id='store-images');
create policy "store images staff insert" on storage.objects for insert to authenticated with check(bucket_id='store-images' and public.is_store_staff());
create policy "store images staff update" on storage.objects for update to authenticated using(bucket_id='store-images' and public.is_store_staff()) with check(bucket_id='store-images' and public.is_store_staff());
create policy "store images staff delete" on storage.objects for delete to authenticated using(bucket_id='store-images' and public.is_store_staff());

notify pgrst,'reload schema';
