-- Dark Matter - Store Supervisor System
-- شغّل هذا الملف مرة واحدة في Supabase > SQL Editor
-- هذا الملف مبني على الجداول الحالية: site_admins / supervisors / orders

create extension if not exists pgcrypto;

-- إعدادات المتجر
create table if not exists public.store_settings (
  id integer primary key default 1 check (id = 1),
  store_title text not null default 'المتجر',
  store_subtitle text not null default 'المنتجات المتوفرة: طاولات التصنيع — انتقال الهليكوبترات — منتج خاص',
  announcement text not null default '',
  store_enabled boolean not null default true,
  updated_at timestamptz not null default now()
);

insert into public.store_settings(id)
values (1)
on conflict (id) do nothing;

-- المنتجات والسيارات
create table if not exists public.store_products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null default 'car'
    check (category in ('car','crafting','helicopter','other')),
  description text not null default '',
  price numeric(10,2) not null default 22.99 check (price >= 0),
  image_url text not null default '',
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- أكواد الخصم
create table if not exists public.discount_codes (
  id uuid primary key default gen_random_uuid(),
  code text not null,
  discount_type text not null check (discount_type in ('percent','fixed')),
  discount_value numeric(10,2) not null check (discount_value >= 0),
  min_order numeric(10,2) not null default 0 check (min_order >= 0),
  max_uses integer null check (max_uses is null or max_uses >= 1),
  used_count integer not null default 0 check (used_count >= 0),
  starts_at timestamptz null,
  expires_at timestamptz null,
  active boolean not null default true,
  created_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists discount_codes_code_lower_uidx
on public.discount_codes (lower(code));

-- حقول الخصم داخل الطلب
alter table public.orders add column if not exists product_id bigint;
alter table public.orders add column if not exists original_price numeric(10,2);
alter table public.orders add column if not exists discount_code text;
alter table public.orders add column if not exists discount_amount numeric(10,2) not null default 0;

-- زرع المنتجات الحالية لأول مرة.
-- الصور القديمة تبقى من index.html، والمشرف يقدر يغير رابط الصورة لاحقاً.
insert into public.store_products(id,name,category,price,sort_order)
values
(1,'انتقال الهليكوبترات','helicopter',22.99,1),
(2,'طاولة تصنيع','crafting',22.99,2),
(3,'سيارة خاصة 3','car',22.99,3),
(4,'سيارة خاصة 4','car',22.99,4),
(5,'سيارة خاصة 5','car',22.99,5),
(6,'سيارة خاصة 6','car',22.99,6),
(7,'سيارة خاصة 7','car',22.99,7),
(8,'سيارة خاصة 8','car',22.99,8),
(9,'سيارة خاصة 9','car',22.99,9),
(10,'سيارة خاصة 10','car',22.99,10),
(11,'سيارة خاصة 11','car',22.99,11),
(12,'سيارة خاصة 12','car',22.99,12),
(13,'سيارة خاصة 13','car',22.99,13),
(14,'سيارة خاصة 14','car',22.99,14),
(15,'سيارة خاصة 15','car',22.99,15),
(16,'سيارة خاصة 16','car',22.99,16),
(17,'سيارة خاصة 17','car',22.99,17),
(18,'سيارة خاصة 18','car',22.99,18),
(19,'سيارة خاصة 19','car',22.99,19),
(20,'سيارة خاصة 20','car',22.99,20),
(21,'سيارة خاصة 21','car',22.99,21),
(22,'سيارة خاصة 22','car',22.99,22),
(23,'سيارة خاصة 23','car',22.99,23),
(24,'سيارة خاصة 24','car',22.99,24),
(25,'سيارة خاصة 25','car',22.99,25),
(26,'سيارة خاصة 26','car',22.99,26),
(27,'سيارة خاصة 27','car',22.99,27),
(28,'سيارة خاصة 28','car',22.99,28),
(29,'سيارة خاصة 29','car',22.99,29),
(30,'سيارة خاصة 30','car',22.99,30),
(31,'سيارة خاصة 31','car',22.99,31),
(32,'سيارة خاصة 32','car',22.99,32),
(33,'سيارة خاصة 33','car',22.99,33),
(34,'سيارة خاصة 34','car',22.99,34),
(35,'سيارة خاصة 35','car',22.99,35),
(36,'سيارة خاصة 36','car',22.99,36),
(37,'سيارة خاصة 37','car',22.99,37),
(38,'سيارة خاصة 38','car',22.99,38),
(39,'سيارة خاصة 39','car',22.99,39),
(40,'سيارة خاصة 40','car',22.99,40),
(41,'سيارة خاصة 41','car',22.99,41),
(42,'سيارة خاصة 42','car',22.99,42)
on conflict (id) do nothing;

select setval(
  pg_get_serial_sequence('public.store_products','id'),
  greatest((select coalesce(max(id),1) from public.store_products), 1),
  true
);

-- صلاحية موحدة للمالك أو المشرف
create or replace function public.is_store_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_site_owner() or public.is_site_supervisor();
$$;

grant execute on function public.is_store_staff() to authenticated;

alter table public.store_settings enable row level security;
alter table public.store_products enable row level security;
alter table public.discount_codes enable row level security;

-- سياسات الإعدادات
drop policy if exists "store settings public read" on public.store_settings;
drop policy if exists "store settings staff update" on public.store_settings;
create policy "store settings public read"
on public.store_settings for select to anon,authenticated
using (true);
create policy "store settings staff update"
on public.store_settings for update to authenticated
using (public.is_store_staff())
with check (public.is_store_staff());

-- سياسات المنتجات
drop policy if exists "store products public active read" on public.store_products;
drop policy if exists "store products staff all read" on public.store_products;
drop policy if exists "store products staff insert" on public.store_products;
drop policy if exists "store products staff update" on public.store_products;
drop policy if exists "store products staff delete" on public.store_products;

create policy "store products public active read"
on public.store_products for select to anon,authenticated
using (active = true);

create policy "store products staff all read"
on public.store_products for select to authenticated
using (public.is_store_staff());

create policy "store products staff insert"
on public.store_products for insert to authenticated
with check (public.is_store_staff());

create policy "store products staff update"
on public.store_products for update to authenticated
using (public.is_store_staff())
with check (public.is_store_staff());

create policy "store products staff delete"
on public.store_products for delete to authenticated
using (public.is_store_staff());

-- سياسات أكواد الخصم: لا نكشف الأكواد للزوار
drop policy if exists "discount staff read" on public.discount_codes;
drop policy if exists "discount staff insert" on public.discount_codes;
drop policy if exists "discount staff update" on public.discount_codes;
drop policy if exists "discount staff delete" on public.discount_codes;

create policy "discount staff read"
on public.discount_codes for select to authenticated
using (public.is_store_staff());

create policy "discount staff insert"
on public.discount_codes for insert to authenticated
with check (public.is_store_staff());

create policy "discount staff update"
on public.discount_codes for update to authenticated
using (public.is_store_staff())
with check (public.is_store_staff());

create policy "discount staff delete"
on public.discount_codes for delete to authenticated
using (public.is_store_staff());

-- إنشاء الطلب من قاعدة البيانات نفسها حتى لا يقدر العميل يغير السعر من المتصفح.
drop policy if exists "buyer creates own order" on public.orders;

create or replace function public.create_store_order(
  p_product_id bigint,
  p_discount_code text default null
)
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  p public.store_products%rowtype;
  d public.discount_codes%rowtype;
  settings public.store_settings%rowtype;
  discount_value_calc numeric(10,2) := 0;
  final_price numeric(10,2);
  result_order public.orders%rowtype;
  code_clean text := nullif(upper(trim(coalesce(p_discount_code,''))), '');
  buyer_email_value text := lower(coalesce(auth.jwt()->>'email',''));
  buyer_name_value text := coalesce(
    auth.jwt()->'user_metadata'->>'full_name',
    auth.jwt()->'user_metadata'->>'name',
    auth.jwt()->'user_metadata'->>'user_name',
    buyer_email_value
  );
begin
  if auth.uid() is null then
    raise exception 'يجب تسجيل الدخول أولاً';
  end if;

  select * into settings from public.store_settings where id = 1;
  if settings.id is not null and not settings.store_enabled then
    raise exception 'المتجر مغلق حالياً';
  end if;

  select * into p
  from public.store_products
  where id = p_product_id and active = true;

  if p.id is null then
    raise exception 'المنتج غير موجود أو غير متاح';
  end if;

  final_price := p.price;

  if code_clean is not null then
    select * into d
    from public.discount_codes
    where upper(code) = code_clean
    limit 1;

    if d.id is null then raise exception 'كود الخصم غير صحيح'; end if;
    if not d.active then raise exception 'كود الخصم غير مفعل'; end if;
    if d.starts_at is not null and now() < d.starts_at then raise exception 'كود الخصم لم يبدأ بعد'; end if;
    if d.expires_at is not null and now() > d.expires_at then raise exception 'انتهت صلاحية كود الخصم'; end if;
    if d.max_uses is not null and d.used_count >= d.max_uses then raise exception 'تم استهلاك كود الخصم'; end if;
    if p.price < d.min_order then raise exception 'سعر المنتج أقل من الحد الأدنى للكود'; end if;

    if d.discount_type = 'percent' then
      discount_value_calc := round(p.price * least(d.discount_value,100) / 100.0, 2);
    else
      discount_value_calc := least(d.discount_value, p.price);
    end if;

    final_price := greatest(0, round(p.price - discount_value_calc, 2));

    update public.discount_codes
    set used_count = used_count + 1, updated_at = now()
    where id = d.id;
  end if;

  insert into public.orders(
    buyer_id,buyer_email,buyer_name,product_id,product_name,
    original_price,discount_code,discount_amount,price,amount_halalas,
    currency,status,payment_status,updated_at
  )
  values(
    auth.uid(),buyer_email_value,buyer_name_value,p.id,p.name,
    p.price,code_clean,discount_value_calc,final_price,round(final_price*100)::integer,
    'SAR','بانتظار الدفع','pending',now()
  )
  returning * into result_order;

  return result_order;
end;
$$;

revoke all on function public.create_store_order(bigint,text) from public;
grant execute on function public.create_store_order(bigint,text) to authenticated;

notify pgrst, 'reload schema';
